info:
  version: 1.0.1
  description: Network Exposure Function Initial Configuration


configuration:
  sbi:
    scheme: http
    registerIPv4: 127.0.0.15
    bindingIPv4: 127.0.0.15
    port: 8000
    tls:
      pem: config/TLS/nef.pem
      key: config/TLS/nef.key
  serviceNameList:
    - 3gpp-as-session-with-qos
    - 3gpp-service-parameter
  nrfUri: http://127.0.0.10:8000


